const express = require('express')
const Router = express.Router()
const UserControl = require('../controller/UserControl')
const hashPassword = require('../middleware/hashPassword')
const TokenController = require('../middleware/TokenController')
const multer = require('multer')
const storage = require('../storage')
const upload = multer({ storage: storage })
Router.get('/getUser/:userId', TokenController.verifyToken, UserControl.getUser)
Router.get('/getAllUsers', TokenController.verifyToken, UserControl.getAllUsers)
Router.get('/compareUser', UserControl.compareUser)
Router.post('/createUser', upload.single('avatar'), hashPassword, UserControl.createUser)
Router.get('/logoutUser', TokenController.verifyToken, UserControl.LogoutUser)
Router.get('/refreshToken', TokenController.refreshToken)
Router.delete('/deleteUser/:userId', TokenController.verifyTokenAndAdmin, UserControl.deleteUser)
module.exports = Router
